name: teach_on_mars_test
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">3.0.0"

dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_generator: ^2.0.0
  http: ^1.1.0
  intl: 0.18.0
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.0.15
  stream_transform: ^2.1.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: "Roboto"
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 700
          style: italic
